version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://test:test@cluster0.mongodb.net/mern?retryWrites=true&w=utf8
    networks:
      - mern-app-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - mern-app-network

networks:
  mern-app-network:
    driver: bridge
